### PR TITLE
9/18/24 production deploy

### PR DESCRIPTION
**Pull request by stvnrlly**
*A note to PR reviewers: it may be helpful to review our [code review documentation](https://github.com/GSA/notifications-api/blob/main/docs/all.md#code-reviews) to know what to keep in mind while reviewing pull requests.*

## Description

Please enter a detailed description here.

This is a production deploy for 9/18/2024.  [Full release notes are here!](https://github.com/GSA/notifications-admin/releases/tag/09-18-2024)

## Security Considerations

* All changes have been reviewed and tested prior to being included here.

### CODE REVIEW

**Review by heyitsmebev — DISMISSED** [review]
LGTM

**Review by ccostino — APPROVED** [review]
🎉

**Review by ccostino — APPROVED** [review]
All previous changes have been approved and this is now good to go out!

**Review by A-Shumway42 — DISMISSED** [review]

**Review by heyitsmebev — APPROVED** [review]
LGTM

**Review by ccostino — APPROVED** [review]
Final approval!

**Pull request merged**
