### PR TITLE
notify-admin-723 end to end tests

### PR DESCRIPTION
**Pull request by terrazoon**
I managed to get all of Carlo's tests to pass.  I don't know why.  I simply removed the skip commands, started up notifications_api and notifications_admin, ran the tests agains the up-and-running app, and made a couple of trivial additions with a decorator that shouldn't really be doing anything -- but actually is somehow creating an authenticated session for the tests that use it, so now they pass.

I imagine this needs some more work.  It's curious that all the tests pass now, though.

### CODE REVIEW

**Comment by ccostino** [comment]
Whoa!  What you did with the decorator is what I had in mind for what to do next, though I wasn't sure how best to bypass based on the environment - this seems even simpler than what I thought would have to happen.

One thing to look into as we dig further is if you run the app locally but set the E2E tests to go against the staging site; what happens then?  Does the user try and authenticate then or can it still bypass?

The other thing to check is if we're able to skip the auth, the test account shouldn't try and sign in either.  Perhaps the call to the `user_api_client.user_api_client.get_all_users()` call is still doing something there, or maybe I saw the MFA codes appear before you got this piece in; either way I'm not sure yet.

All that said, this is definitely progress, thank you @terrazoon!

**Comment by terrazoon** [comment]
I changed to staging in my .env file:


NOTIFY_E2E_TEST_URI=https://notify-staging.app.cloud.gov/

And now the tests in test_landing_and_signin_pages.py fail with the following error.  But the workflow tests still pass.


E       playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
E       =========================== logs ===========================
E       waiting for get_by_role("link", name="Sign in")
E       ============================================================

**Comment by terrazoon** [comment]
And then if I apply the @skip_auth_for_tests to the tests in test_landing_and_sign_in_pages.py, everything passes!  Quite magical.

**Comment by ccostino** [comment]
@terrazoon I'm going to pull this down locally and try to see if I can figure out what's going on under the hood that's allowing for this - I'll report back if we need to make any further adjustments!

**Comment by ccostino** [comment]
Okay after pulling this down and going through things locally (and that being after I rebased the PR with `main` to pull in the `poetry` updates), I've noticed a couple of things:

- Removing the decorator does indeed cause all of the tests to fail
- Adding the decorator makes all the tests pass almost instantly

I tried to drop into a `pdb` session within the decorator itself (inside the inner function where it checks the `NOTIFY_ENVIRONMENT` env-var) and noticed that `pytest` didn't stop, so I tried forcing an `Exception` to be raised, and that didn't stop either.  So, it would appear the decorator is flat out preventing the tests from actually running!

I'm reasonably sure that the tests now fail because they're not accounting for the full browser context that requires the HTTP Basic auth info, at least in the case of targeting staging.  We'll have to work the `pytest` fixture back in, at least the non-authenticated one.

I think that the `skip_auth_for_tests` decorator itself should be moved into the test config as opposed to being part of the app utils themselves because it's specifically related to the E2E test config.  As for what should be _in_ the decorator...  that's the mystery!  I was curious to see what the API call was actually returning so that's as good a place as any to start once we get these things wired up properly so they behave as expected. :-)

**Pull request closed without merging**
