### PR TITLE
change download reports to 12 hour time (notify-admin-1090)

### PR DESCRIPTION
**Pull request by terrazoon**

### CODE REVIEW

**Review by heyitsmebev — APPROVED** [review]
Looks good and works when I download report within the Recent batch table
image

**Review by heyitsmebev — COMMENTED** [review]
I notice the title of the csv file still shows the 24 hour time 
image

**Comment by terrazoon** [comment]
> I notice the title of the csv file still shows the 24 hour time

Updated to:   2024-01-24 11_50_27 AM - sms - k1 report.csv

**Review by ccostino — APPROVED** [review]
Awesome, thank you @terrazoon and thank you @heyitsmebev for taking a look and reviewing as well! 🎉

**Pull request merged**
