### PR TITLE
1669 - toggle between recent activity and all activity

### PR DESCRIPTION
**Pull request by jonathanbobel**
# Description

Allow for the dashboard dropdown to toggle between the All Activity and My Activity table

## TODO

- [x] Users can toggle between viewing all Recent Activity for their service and Recent Activity from a single user profile.
- [x] Review recent dahsboard [prototype ](https://www.figma.com/proto/aAWhlPzOP6kfVFnCCAfSZZ/notify.gov?page-id=3047%3A4396&type=design&node-id=3047-5482&viewport=1545%2C-388%2C0.39&t=hcILYUjGtf62EHzn-1&scaling=min-zoom&starting-point-node-id=3047%3A4580). Note that when a user selects `Account` drop down the Recent Activity table toggles between `All Service Activity` and `My Activity`, similar to the data viz.
- [x] Build an MVP of the `Recent Activity `Table that toggles table display from `All Activity` to `My Activity`, which will display jobs sent by user (filtering out jobs sent by other users).
- [x] Ensure this table works with real indvidual-level data.

### CODE REVIEW

**Review by terrazoon — APPROVED** [review]

**Review by terrazoon — COMMENTED** [review]
Code looks good but I see there's a failing test.  I can't seem to unable so approval is contingent on tests passing. :)

**Comment by ccostino** [comment]
@jonathanbobel this just needs another sync with `main` it looks like and then should be good to go!

**Comment by jonathanbobel** [comment]
This code was merged in part of a previous issue. Closing.

**Comment by jonathanbobel** [comment]
This code was merged in part of a previous issue. Closing.

**Pull request closed without merging**
