### PR TITLE
Production deploy 10/31/23

### PR DESCRIPTION
**Pull request by stvnrlly**
# Major changes
- Add a session timer with a 30-minute timeout (#750 )
- Enable analytics (#872 )

# Minor changes
- UI improvements (#856 #816 #846 #849 )
- Clean up test config (#748 )

### CODE REVIEW

**Review by ccostino — DISMISSED** [review]
Thanks, @stvnrlly and @tdlowden!

**Comment by tdlowden** [comment]
### Manual QA Checklist


**Log-in**


- [ ] notify-staging.app.cloud.gov resolves
- [ ] Clicking sign in takes you to login page
- [ ] 2FA code is sent promptly
- [ ] 2FA code input screen appears as expected
- [ ] After code is entered, you are brought to the “choose service” screen
- [ ] Choosing a service brings you to the dashboard for that service


**Create a template and send**
- [ ] Clicking “Send messages” brings you to templates page
- [ ] When “Create a template” button is clicked, the option to create new or copy existing template appears
- [ ] Uploading a csv is quick and automatically directs you to the preview/send page
- [ ] Formatting looks clean and in place
- [ ] Message dashboard populates and shows “pending” until call is made to AWS for delivery receipt


**Send a message from copied template**
- [ ] When “Create a template” button is clicked, the option to create new or copy existing template appears
- [ ] Clicking “copy an existing template” allows you to choose from pre-existing template
- [ ] After editing, the new template saves and you prepare to send


**Send a message from existing template**
- [ ] Clicking on existing template brings you to preview screen with `prepare to send` button
- [ ] All else above persists as true (formatting, send, dashboard, etc)


**Download the csv delivery report**
- [ ] Clicking on the csv download directly after a message send downloads a report that contains the data we expect
- [ ] Clicking on the csv download link from the 7-day aggregated dashboard downloads a report that contains the data we expect


**Invite a team member**
- [ ] Clicking on “Team Members” in left nav brings you to team member screen
- [ ] Clicking “Invite a team member” brings you to email and permissions screen
- [ ] Clicking invite team member sends an invite and shows confirmation
- [ ] Invite email provides live link that works to register new team member


**Delete a team member**
- [ ] From team member screen, clicking “Change Details” on a specific profile brings you to that person’s profile
- [ ] Clicking on “Remove this team member” prompts a confirmation
- [ ] Clicking the confirmation removes the team member


**Sign out**
- [ ] Hitting “Sign Out” takes you back to the homepage and logs you out

**Review by tdlowden — DISMISSED** [review]
QA script completed after snafu with GSA email yesterday.

**Review by ccostino — APPROVED** [review]
Approving again.

**Pull request merged**
