### PR TITLE
Localize notification_utils to the admin

### PR DESCRIPTION
**Pull request by ccostino**
*A note to PR reviewers: it may be helpful to review our [code review documentation](https://github.com/GSA/notifications-api/blob/main/docs/all.md#code-reviews) to know what to keep in mind while reviewing pull requests.*

## Description

This changeset pulls in all of the `notification_utils` code directly into the admin and removes it as an external dependency. We are doing this to cut down on operational maintenance of the project and will begin removing parts of it no longer needed for the admin.

## Security Considerations

- This removes the `notification_utils` repo as a dependency but maintains all of the others that were included with it. We'll be removing anything we don't need over time, but until we can we'll have to make sure they all stay up-to-date.

### CODE REVIEW

**Comment by xlorepdarkhelm** [comment]
Looks like flake8 "asploded".

**Comment by ccostino** [comment]
@xlorepdarkhelm  Yes it did, and it's even more amazing to me that it _didn't_ in the API PR given it's _the same code_...!  :sigh:... 😆

**Comment by xlorepdarkhelm** [comment]
I would check what flake8 plugins are installed between the two, as there is obviously a difference. Looks like admin has a flake8 extension just for pytest?

**Comment by ccostino** [comment]
@terrazoon will tackle fixing all of the test warnings.  Once that's taken care of, I'll copy all of the changes to the [API PR](https://github.com/GSA/notifications-api/pull/998) to make sure we have them there, too.  Thank you!

**Review by terrazoon — APPROVED** [review]

**Pull request merged**
