### PR TITLE
Upgrade Node.js to the latest stable release

### PR DESCRIPTION
**Pull request by terrazoon**
## Description

1. Upgrade node from v16.15.1 to v22.3.0 (latest)
2. Upgrade seven or eight dependencies, so only 4 are left when we run `npm outdated`

The remaining 4 dependencies are more problematical.  

Upgrading gulp to 5.0.0 appears to trigger an error in USWDS compile, which also relies on the old gulp 4.0.2 we use.  So we may (?) need to wait for USWDS to upgrade before we can do so.  I'm not clear on this.  But if gulp versions are mismatched, USWDS compile will fail because it can't find the folder 'undefinedassets/images'

## Security Considerations

Get more secure by updating our tools.

### CODE REVIEW

**Comment by alexjanousekGSA** [comment]
It looks like a few more of those outdated dependencies could be updated:

- npm install morphdom@2.7.3
- npm install govuk_frontend_toolkit@9.0.1
- npm install govuk-frontend@5.4.0

I was also then able to run - npm install gulp@4.0.2


Then the only outdated dependency was rollup which i could not get working. Looking into what is needed for that to work now. 



-

**Comment by ccostino** [comment]
Thanks, @alexjanousekGSA!  If it turns out that it's easier to do this in phases and the build errors continue, then let's make that a next step, no need to try and get it all working in one go! 🙂

**Comment by alexjanousekGSA** [comment]
> Thanks, @alexjanousekGSA! If it turns out that it's easier to do this in phases and the build errors continue, then let's make that a next step, no need to try and get it all working in one go! 🙂

I think that would be a good idea, especially since there is a security update coming out next week - https://nodejs.org/en/blog/vulnerability/july-2024-security-releases

Might be a good idea to get this in, then do another incremental approach. It looks like the big issue here is the gulp is using a plugin that uses an older version of rollup. So a replacement needs to be found and used and then we can update rollup to version 4 (which is probably way better too). Ill continue looking into this today, but it might take a bit of trial and error.

**Review by alexjanousekGSA — APPROVED** [review]

**Comment by ccostino** [comment]
Awesome, thank you @terrazoon and @alexjanousekGSA for diving into this!  It's been on the laundry list of things to but we had a bunch on the Python side to tackle first...  Nice to see us being able to get some 👀 on this now!

@alexjanousekGSA, please write up a new issue for the follow-on work you mentioned and continue on with that; I'll get it tracked in the right epic once it's on the board.

I'll take a final look at things here now that we're ready to go. Thank you both!

**Review by ccostino — APPROVED** [review]
Thank you, @terrazoon for tackling this, and @alexjanousekGSA for taking a second look and updating the docs!

I'm noting a couple of things here, but they're fine for this going through:

* This PR includes an update to `poetry.lock`, which appears to be pulling in a `flake8` update; this should've been it's own PR, but Python dependencies are hard to merge right now in the admin because of the E2E thing with Dependabot, so it's fine for here.  I updated the `pyproject.toml` file to match.
* We should include a note or let folks know about updating their own `.env` file in the admin to make sure `NODE_VERSION` is set to `22.3.0`; it's not a showstopper as things will still work (I think primarily because of the `.nvmrc` file), but better to make sure that things are set properly to begin with. :-)

Thank you both again, this is awesome to see!

**Pull request merged**
