### PR TITLE
Added new header button that is displayed in header

### PR DESCRIPTION
**Pull request by alexjanousekGSA**
Added new button in header that allows one to navigate to login from the /about page and other static pages when not logged in. It is currently hidden behind the about feature flag until these pages are fully released. 

The new button is only on the /about page and not on the homepage. 
image

image

### CODE REVIEW

**Review by jonathanbobel — APPROVED** [review]
LGTM - I know this is still work to be done, but we'll have to have the top nav in these pages as well (About, Join Notify, Contact) and the login.gov button on any page before the login that isn't the home page

**Review by heyitsmebev — COMMENTED** [review]
Is it expected to get this error when I click on the login button?
image

**Comment by alexjanousekGSA** [comment]
> Is it expected to get this error when I click on the login button? image

No that is not expected. Are you sure that you have the environment variable in your .env for the login urls? Its using those and maybe if it doesn't exist it wont work?

**Comment by heyitsmebev** [comment]
@alexjanousekGSA when i click on the button on the homepage, i do not get those errors. Are there additional login env i should consider here? 
image

**Review by heyitsmebev — APPROVED** [review]
LGTM

**Review by xlorepdarkhelm — APPROVED** [review]

**Pull request merged**
