### PR TITLE
About Security Content

### PR DESCRIPTION
**Pull request by heyitsmebev**
As part of the new About Notify content section, this PR is the implementation for "Security"
image

Definition of Done

- Should include a side navigation
- Should be able to easily navigate to About Notify content
- Should meet a11y standards

Figma:
https://www.figma.com/proto/aAWhlPzOP6kfVFnCCAfSZZ/notify.gov?page-id=2339%3A3817&node-id=5392-875&node-type=frame&viewport=2870%2C-701%2C0.48&t=nfkxOXnOCIFQB1yK-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=5392%3A875

Content:
https://docs.google.com/document/d/1lP8I0Jxu0B26cmTGBQcoHCbfSvKKHQBE6gzTL9HUheE/edit?tab=t.0#heading=h.icyigvoln8tg

### CODE REVIEW

**Comment by jonathanbobel** [comment]
@heyitsmebev all links that leave the Notify.gov site need an external link icon added
https://designsystem.digital.gov/components/link/

Example:
`
 <a
    class="usa-link usa-link--external"
    rel="noreferrer"
    target="_blank"
    href="https://i.giphy.com/media/WPzQF6ruiIIVzHNlwX/source.gif"
    >external website</a
  >.
  `

**Review by alexjanousekGSA — APPROVED** [review]

**Comment by dmvancura** [comment]
Security is a subpage to the About Notify section. It is navigated to after a user selects to view the About Notify section. @CathyBeil and @jonathanbobel, correct, yes? Note: It is in front of the login, but i understand that's a different PR.

**Comment by heyitsmebev** [comment]
@dmvancura i revised the menu hierarchy in this PR. We are set there

**Review by jonathanbobel — APPROVED** [review]
LGTM

**Comment by dmvancura** [comment]
anything else needed on 2127? github is a bit confusing and i can't tell by looking through this, so let me know if i need to help with anything else @jonathanbobel

**Pull request merged**
