### PR TITLE
Create notify-pilot-flyer.md

### PR DESCRIPTION
**Pull request by tdlowden**
pandoc ftw

### CODE REVIEW

**Comment by stvnrlly** [comment]
Looks good, but do you want to link to this file from somewhere like the README?

**Review by stvnrlly — APPROVED** [review]
Looks good, but do you want to link to this file from somewhere like the README?

**Comment by tdlowden** [comment]
@stvnrlly I do. I will make that change in this branch as well. ty

**Comment by tdlowden** [comment]
ok @stvnrlly should be good now!

**Review by stvnrlly — APPROVED** [review]
Nice! I think this content would be great in the API repo as well.

**Pull request merged**
