### PR TITLE
Create BUG-TEMPLATE.yml

### PR DESCRIPTION
**Pull request by tdlowden**

### CODE REVIEW

**Comment by jonathanbobel** [comment]
@tdlowden looks good, I would maybe add a spot for screenshots as well besides just the URL (if there's even a way to do that?)

**Comment by jonathanbobel** [comment]
If there isn't a programmatic way, we can encourage the bug issue creator to add them in later if it's helpful

**Comment by tdlowden** [comment]
Great point. I wonder if I can just leave an open area to do so. Let me see what I can do

**Comment by tdlowden** [comment]
@jonathanbobel I ended up just adding a line about putting screenshots in comments. Couldn't find a way to specify an upload zone in markdown. But it is telling me theres a syntax error. Maybe we approve this and see what it does, then I can fix?

**Review by jonathanbobel — APPROVED** [review]

**Pull request merged**
